### ISSUE TITLE
[Spike] Setup DocumentDB

### ISSUE THREAD

**Issue by jsstrn** [developer-program/engineering-track#18]
Conclusion: DocumentDB is not suitable for our use case and we should either use MongoDB Atlas or run MongoDB on AWS

**Comment by kaiNext** [comment]
Pros
- Easily scalable
- Highly available
- AWS Includes migration service

Cons
- Stuck with mongodb 3.6 features
- Low compatibility with mongodb, see [https://www.percona.com/blog/2019/12/20/mongodb-compatibility-in-aws-documentdb/](https://www.percona.com/blog/2019/12/20/mongodb-compatibility-in-aws-documentdb/)
- Expensive (min 200USD per mth)

I feel this is not the right db as the advantages over mongodb don't really matter for our use case. There is a risk of some incompatibility and is extremely expensive compared to other alternatives like mongo on ec2.

**Comment by kaiNext** [comment]
**Alternatives**
- Install mongodb on EC2 instance
See https://docs.mongodb.com/manual/tutorial/install-mongodb-on-amazon/
- Use AMI with mongodb installed

**Connecting express app to mongodb instance**
- https://stackoverflow.com/questions/51764695/cant-connect-to-my-mongodb-ec2-instance-via-nodejs

**Comment by jsstrn** [comment]
@kai-tw thanks for researching on the suitability of DocumentDB. 

Another option is to use [MongoDB Atlas](https://www.mongodb.com/cloud/atlas)
